const K={users:'shophub-admin-users-v1',sellers:'shophub-admin-sellers-v1',products:'shophub-admin-products-v1',orders:'shophub-orders-v1',reviews:'shophub-reviews-v1',categories:'shophub-admin-categories-v1'};
const seedUsers=[
  {id:'CU-10482',name:'Olivia Martin',email:'olivia.martin@example.com',role:'Customer',status:'Active',joined:'2026-08-12',orders:4,wishlist:6,reviews:2},
  {id:'CU-10461',name:'Linh Tran',email:'linh.tran@example.com',role:'Customer',status:'Active',joined:'2026-07-28',orders:7,wishlist:3,reviews:4},
  {id:'CU-10398',name:'James Wilson',email:'james.wilson@example.com',role:'Customer',status:'Active',joined:'2026-06-14',orders:2,wishlist:9,reviews:1},
  {id:'CU-10352',name:'Amelia Brooks',email:'amelia.brooks@example.com',role:'Customer',status:'Disabled',joined:'2026-04-03',orders:5,wishlist:2,reviews:3},
  {id:'CU-10277',name:'Noah Kim',email:'noah.kim@example.com',role:'Customer',status:'Active',joined:'2026-02-21',orders:3,wishlist:4,reviews:1},
  {id:'SE-20412',name:'Maya Chen',email:'hello@sundayobjects.example',role:'Seller',status:'Active',joined:'2025-11-18',shop:'Sunday Objects',orders:38,wishlist:0,reviews:71},
  {id:'SE-20384',name:'Nora Ellis',email:'hello@northandtone.example',role:'Seller',status:'Active',joined:'2025-10-09',shop:'North & Tone',orders:64,wishlist:0,reviews:248},
  {id:'SE-20341',name:'Marlow James',email:'studio@marlowgoods.example',role:'Seller',status:'Active',joined:'2025-08-22',shop:'Marlow Goods',orders:51,wishlist:0,reviews:182},
  {id:'SE-20298',name:'Ava Flores',email:'shop@commonground.example',role:'Seller',status:'Active',joined:'2025-07-11',shop:'Common Ground',orders:29,wishlist:0,reviews:96},
  {id:'SE-20217',name:'Wilder Park',email:'hello@wilderhome.example',role:'Seller',status:'Active',joined:'2025-05-02',shop:'Wilder Home',orders:22,wishlist:0,reviews:88},
  {id:'SE-20168',name:'Rae Morgan',email:'care@kindredsupply.example',role:'Seller',status:'Active',joined:'2025-03-25',shop:'Kindred Supply',orders:31,wishlist:0,reviews:62},
  {id:'SE-20120',name:'Tessa Green',email:'hello@brightnest.example',role:'Seller',status:'Pending',joined:'2026-10-03',shop:'Bright Nest',orders:0,wishlist:0,reviews:0},
  {id:'SE-20097',name:'Eli Parker',email:'studio@paperandpine.example',role:'Seller',status:'Pending',joined:'2026-10-01',shop:'Paper & Pine',orders:0,wishlist:0,reviews:0},
  {id:'AD-00001',name:'ShopHub Operations',email:'operations@shophub.example',role:'Admin',status:'Active',joined:'2024-01-08',orders:0,wishlist:0,reviews:0}
];
const seedSellers=[
  {id:'SE-20412',name:'Maya Chen',email:'hello@sundayobjects.example',shop:'Sunday Objects',status:'Approved',joined:'2025-11-18',rating:4.9,description:'Hand-finished stoneware and thoughtful pieces for a slower home.'},
  {id:'SE-20384',name:'Nora Ellis',email:'hello@northandtone.example',shop:'North & Tone',status:'Approved',joined:'2025-10-09',rating:4.8,description:'Everyday audio, tuned for clear and comfortable listening.'},
  {id:'SE-20341',name:'Marlow James',email:'studio@marlowgoods.example',shop:'Marlow Goods',status:'Approved',joined:'2025-08-22',rating:4.8,description:'Small-batch leather accessories made to be carried every day.'},
  {id:'SE-20298',name:'Ava Flores',email:'shop@commonground.example',shop:'Common Ground',status:'Approved',joined:'2025-07-11',rating:4.7,description:'Comfortable everyday shoes with considered materials.'},
  {id:'SE-20217',name:'Wilder Park',email:'hello@wilderhome.example',shop:'Wilder Home',status:'Approved',joined:'2025-05-02',rating:4.8,description:'Soft natural textiles for quiet, lived-in spaces.'},
  {id:'SE-20168',name:'Rae Morgan',email:'care@kindredsupply.example',shop:'Kindred Supply',status:'Approved',joined:'2025-03-25',rating:4.7,description:'Useful outdoor goods for small adventures.'},
  {id:'SE-20120',name:'Tessa Green',email:'hello@brightnest.example',shop:'Bright Nest',status:'Pending',joined:'2026-10-03',rating:0,description:'Handwoven storage and small-batch home organizers.'},
  {id:'SE-20097',name:'Eli Parker',email:'studio@paperandpine.example',shop:'Paper & Pine',status:'Pending',joined:'2026-10-01',rating:0,description:'Recycled paper goods and stationery made for everyday notes.'}
];
const seedCategories=[
  {id:'cat-home',name:'Home & living',parent:'',status:'Active',sort:1,description:'Considered pieces for a comfortable home.'},
  {id:'cat-accessories',name:'Accessories',parent:'',status:'Active',sort:2,description:'Everyday bags and thoughtful finishing touches.'},
  {id:'cat-shoes',name:'Shoes',parent:'',status:'Active',sort:3,description:'Comfortable shoes for daily movement.'},
  {id:'cat-tech',name:'Tech & audio',parent:'',status:'Active',sort:4,description:'Useful technology and listening essentials.'},
  {id:'cat-outdoors',name:'Outdoors',parent:'',status:'Active',sort:5,description:'Useful goods for time spent outside.'},
  {id:'sub-lighting',name:'Lighting',parent:'Home & living',status:'Active',sort:1,description:'Table and ambient lighting.'},
  {id:'sub-kitchen',name:'Kitchen & dining',parent:'Home & living',status:'Active',sort:2,description:'Thoughtful pieces for cooking and gathering.'},
  {id:'sub-bags',name:'Bags',parent:'Accessories',status:'Active',sort:1,description:'Carryalls and everyday bags.'},
  {id:'sub-audio',name:'Audio',parent:'Tech & audio',status:'Active',sort:1,description:'Headphones and compact speakers.'}
];
const ui={section:'dashboard',query:'',filters:{},sort:'recent',page:1,detail:null,modal:null,toastTimer:0};
let bridge;
const clone=value=>JSON.parse(JSON.stringify(value));
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>new Intl.NumberFormat(bridge.getLanguage()==='vi'?'vi-VN':'en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(value)||0);
const date=value=>value?new Intl.DateTimeFormat(bridge.getLanguage()==='vi'?'vi-VN':'en-US',{year:'numeric',month:'short',day:'numeric'}).format(new Date(`${value}T12:00:00`)):bridge.t('—');
function read(key,fallback){try{const value=sessionStorage.getItem(key);if(value!==null){const parsed=JSON.parse(value);return parsed;}sessionStorage.setItem(key,JSON.stringify(fallback));}catch{}return clone(fallback);}
function write(key,value){try{sessionStorage.setItem(key,JSON.stringify(value));}catch{}return value;}
function users(){return read(K.users,seedUsers);}
function sellers(){return read(K.sellers,seedSellers);}
function categoryRows(){return read(K.categories,seedCategories);}
function productStates(){return read(K.products,{});}
function saveProductStates(value){write(K.products,value);}
function getOrders(){return bridge.readOrders().map((order,index)=>{const payment=bridge.orderPayment(order),shipping=bridge.orderShipping(order),raw=String(order.paymentStatus||payment.status).toLowerCase(),paymentStatus=raw.includes('refund')?'Refunded':raw.includes('fail')?'Failed':raw.includes('paid')||raw.includes('authorized')?'Paid':'Pending';return{...order,customer:order.customer||['Olivia Martin','James Wilson','Linh Tran','Amelia Brooks','Noah Kim'][index%5],paymentStatus,paymentMethod:order.paymentMethod||payment.method,shipping:order.shipping||shipping,updatedAt:order.updatedAt||order.date,adminIssue:order.adminIssue||''};});}
function saveOrders(rows){bridge.writeOrders(rows);}
function allProducts(){const rows=[...bridge.products];for(const row of bridge.readSellerManagedProducts()){if(!rows.some(product=>product.id===row.id))rows.push(bridge.sellerManagedCustomerProduct(row));}return rows.map(product=>({...product,...(productStates()[product.id]||{}),shop:product.shop||'Sunday Objects'}));}
function productState(product){return product.moderation||((product.status==='Archived')?'Archived':product.status==='Draft'?'Pending':'Approved');}
function getReviews(){const rows=bridge.readReviews();let changed=false;Object.entries(rows).forEach(([key,row],index)=>{if(row.status==='submitted'||row.status==='edited'){if(!row.moderationStatus){row.moderationStatus='Visible';changed=true;}if(index===1&&row.reported===undefined){row.reported=true;row.reportReason='Customer reported a product claim that may need review.';changed=true;}}});if(changed)bridge.writeReviews(rows);return rows;}
function saveReviews(rows){bridge.writeReviews(rows);}
function productById(id){return allProducts().find(row=>row.id===id)||allProducts()[0];}
function productShopCount(shop){return allProducts().filter(row=>row.shop===shop).length;}
function sellerCounts(seller){const rows=allProducts().filter(product=>product.shop===seller.shop),orders=getOrders().filter(order=>order.shop===seller.shop);const reviews=Object.values(getReviews()).filter(review=>review.shop===seller.shop&&['submitted','edited'].includes(review.status));return{products:rows.length,active:rows.filter(row=>productState(row)==='Approved').length,orders:orders.length,reviews:reviews.length};}
function orderTotal(order){return bridge.orderTotal(order);}
function navItems(){return[['dashboard','/admin','grid','Dashboard'],['users','/admin/users','user','Users'],['sellers','/admin/sellers','store','Sellers & shops'],['products','/admin/products','bag','Products'],['orders','/admin/orders','cart','Orders'],['reviews','/admin/reviews','star','Reviews'],['categories','/admin/categories','layers','Categories']];}
function portalHeader(){return `<header class="admin-topbar"><a class="admin-brand" href="/admin" aria-label="ShopHub Admin"><span class="admin-brand-mark">${bridge.icon('grid',18)}</span><span>ShopHub <b>Admin</b></span></a><span class="admin-environment"><i></i>${bridge.t('Prototype workspace')}</span><div class="admin-top-actions"><div class="admin-language" role="group" aria-label="${bridge.t('Choose language')}"><button type="button" data-language="en" aria-pressed="${bridge.getLanguage()==='en'}">EN</button><span>/</span><button type="button" data-language="vi" aria-pressed="${bridge.getLanguage()==='vi'}">VI</button></div><span class="admin-avatar">OP</span><span class="admin-user-name">${bridge.t('Operations')}</span><a href="/" class="admin-market-link">${bridge.t('Customer marketplace')} ${bridge.icon('arrow',14)}</a></div></header>`;}
function sidebar(){return `<aside class="admin-sidebar"><div class="admin-sidebar-intro"><span class="admin-sidebar-icon">${bridge.icon('settings',17)}</span><div><strong>${bridge.t('Admin Portal')}</strong><small>${bridge.t('Marketplace operations')}</small></div></div><p class="admin-nav-label">${bridge.t('WORKSPACE')}</p><nav aria-label="${bridge.t('Admin navigation')}">${navItems().map(([id,href,ico,label])=>`<a class="admin-nav-link ${ui.section===id?'is-active':''}" href="${href}" ${ui.section===id?'aria-current="page"':''}>${bridge.icon(ico,17)}<span>${bridge.t(label)}</span>${id==='sellers'&&sellers().filter(row=>row.status==='Pending').length?`<b>${sellers().filter(row=>row.status==='Pending').length}</b>`:''}</a>`).join('')}</nav><div class="admin-sidebar-foot"><span>${bridge.icon('info',15)}</span><p>${bridge.t('Sample workspace only. Changes stay in this browser session.')}</p></div></aside>`;}
const titles={dashboard:['Admin overview','A clear view of marketplace health and work that needs attention.'],users:['User management','Review customer, seller, and administrator accounts.'],sellers:['Seller & shop management','Review applications and keep marketplace shops in good standing.'],products:['Product moderation','Review marketplace listings and manage product visibility.'],orders:['Global order management','Search orders across every ShopHub shop.'],reviews:['Review moderation','Keep customer feedback useful, authentic, and visible.'],categories:['Category management','Organize the marketplace browse experience.']};
function shell(){const [title,subtitle]=titles[ui.section];document.title=`${bridge.t(title)} — ShopHub Admin`;return `${portalHeader()}<div class="admin-mobile-nav">${navItems().map(([id,href,ico,label])=>`<a class="${ui.section===id?'is-active':''}" href="${href}">${bridge.icon(ico,15)}<span>${bridge.t(label)}</span></a>`).join('')}</div><div class="admin-layout">${sidebar()}<main class="admin-main"><div class="admin-main-heading"><div><p class="admin-eyebrow">${bridge.t('SHOPHUB OPERATIONS')}</p><h1>${bridge.t(title)}</h1><p>${bridge.t(subtitle)}</p></div>${ui.section==='dashboard'?`<a class="admin-button admin-button-primary" href="/admin/sellers?status=Pending">${bridge.icon('check',16)} ${bridge.t('Review seller applications')}</a>`:''}</div><div id="admin-panel">${content()}</div><p class="admin-prototype-note">${bridge.icon('info',14)} ${bridge.t('Admin changes are sample actions. No real account, listing, order, or payment was changed.')}</p></main></div>${modalMarkup()}`;}
function render(){const app=document.querySelector('#app');app.innerHTML=shell();wireModalFocus();}
function refresh(keep){const target=document.querySelector('#admin-panel');if(!target){render();return;}const active=keep?document.activeElement:null,selector=active?.id?`#${CSS.escape(active.id)}`:null,start=active?.selectionStart,end=active?.selectionEnd;target.innerHTML=content();if(selector){const next=document.querySelector(selector);next?.focus();if(next&&typeof start==='number')next.setSelectionRange(start,end);}}
function stat(label,value,note,icon,tone='green',href=''){return `<a class="admin-stat-card ${tone}" ${href?`href="${href}"`:''}><span class="admin-stat-icon">${bridge.icon(icon,18)}</span><small>${bridge.t(label)}</small><strong>${value}</strong><span class="admin-stat-note">${note}</span></a>`;}
function badge(value){const key=String(value||'Unknown').toLowerCase().replace(/[^a-z0-9]+/g,'-');return `<span class="admin-badge admin-badge-${key}"><i></i>${bridge.t(value||'Unknown')}</span>`;}
function empty(title,copy,action=''){return `<div class="admin-empty"><span>${bridge.icon('search',22)}</span><h3>${bridge.t(title)}</h3><p>${bridge.t(copy)}</p>${action}</div>`;}
function pagination(total){const pages=Math.max(1,Math.ceil(total/5));ui.page=Math.min(ui.page,pages);return `<div class="admin-pagination"><span>${bridge.t('Showing')} ${total?((ui.page-1)*5+1):0}–${Math.min(ui.page*5,total)} ${bridge.t('of')} ${total} ${bridge.t('records')}</span><div><button type="button" data-admin-page="${ui.page-1}" ${ui.page<=1?'disabled':''}>${bridge.t('Previous')}</button><b>${ui.page} / ${pages}</b><button type="button" data-admin-page="${ui.page+1}" ${ui.page>=pages?'disabled':''}>${bridge.t('Next')}</button></div></div>`;}
function paginate(rows){const total=rows.length;return{rows:rows.slice((ui.page-1)*5,ui.page*5),foot:pagination(total),total};}
function table(headers,rows,emptyState){if(!rows.length)return emptyState;return `<div class="admin-table"><div class="admin-table-head">${headers.map(head=>`<span>${bridge.t(head)}</span>`).join('')}</div>${rows.join('')}</div>`;}
function content(){return ({dashboard:dashboardPage,users:usersPage,sellers:sellersPage,products:productsPage,orders:ordersPage,reviews:reviewsPage,categories:categoriesPage}[ui.section]||dashboardPage)();}
function sectionToolbar(searchPlaceholder,filters='',sort=''){return `<div class="admin-toolbar"><label class="admin-search">${bridge.icon('search',16)}<span class="sr-only">${bridge.t('Search')}</span><input type="search" id="admin-search" value="${esc(ui.query)}" placeholder="${bridge.t(searchPlaceholder)}"></label><div class="admin-filters">${filters}</div>${sort?`<label class="admin-sort"><span>${bridge.t('Sort by')}</span><select id="admin-sort">${sort}</select></label>`:''}</div>`;}
function option(value,label,selected=''){return `<option value="${esc(value)}" ${selected===value?'selected':''}>${bridge.t(label)}</option>`;}
function cell(label,value,extra=''){return `<span class="admin-cell ${extra}" data-label="${bridge.t(label)}">${value}</span>`;}
function actionButton(action,id,label,icon='arrow',kind='quiet'){return `<button class="admin-row-action ${kind}" type="button" data-admin-action="${action}" data-id="${esc(id)}">${bridge.icon(icon,14)}<span>${bridge.t(label)}</span></button>`;}
function panel(title,content,extra=''){return `<section class="admin-panel ${extra}"><div class="admin-panel-heading"><div><h2>${bridge.t(title)}</h2></div></div>${content}</section>`;}
function dashboardPage(){
 const all=allProducts(),orders=getOrders(),reviewRows=Object.values(getReviews()).filter(row=>['submitted','edited'].includes(row.status)),pendingSellers=sellers().filter(row=>row.status==='Pending'),pendingProducts=all.filter(row=>productState(row)==='Pending'),reported=reviewRows.filter(row=>row.reported&&row.moderationStatus!=='Hidden'),issues=orders.filter(row=>row.adminIssue&&!row.issueResolved),gmv=orders.filter(row=>row.status!=='cancelled').reduce((sum,row)=>sum+orderTotal(row),0);
 const metrics=`<section class="admin-stats-grid">${stat('Total users',users().length,bridge.t('{count} customer and seller accounts',{count:users().filter(row=>row.role!=='Admin').length}),'user')}${stat('Sellers & shops',sellers().length,bridge.t('{count} awaiting approval',{count:pendingSellers.length}),'store','peach','/admin/sellers')}${stat('Total products',all.length,bridge.t('{count} awaiting moderation',{count:pendingProducts.length}),'bag','lilac','/admin/products')}${stat('Total orders',orders.length,bridge.t('{count} need attention',{count:issues.length}),'cart','blue','/admin/orders')}${stat('GMV / revenue',money(gmv),bridge.t('Across sample orders'),'sparkle','gold')}${stat('Reported reviews',reported.length,bridge.t('{count} order issues open',{count:issues.length}),'star','rose','/admin/reviews')}</section>`;
 const recentOrders=orders.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(order=>`<div class="admin-table-row dashboard-order-row">${cell('Order ID',`<strong>${esc(order.id)}</strong>`)}${cell('Customer',esc(order.customer))}${cell('Shop',esc(order.shop))}${cell('Order total',`<strong>${money(orderTotal(order))}</strong>`)}${cell('Status',badge(order.status))}${cell('Date',date(order.date))}${cell('Actions',actionButton('detail-order',order.id,'View order','arrow'))}</div>`);
 const registrations=sellers().slice().sort((a,b)=>b.joined.localeCompare(a.joined)).slice(0,4).map(seller=>`<a class="admin-activity-row" href="/admin/sellers?status=${encodeURIComponent(seller.status)}"><span class="admin-activity-icon peach">${bridge.icon('store',16)}</span><span><strong>${esc(seller.shop)}</strong><small>${esc(seller.name)} · ${date(seller.joined)}</small></span>${badge(seller.status)}</a>`).join('');
 const activity=[['Product approved','Sunday Ceramic Vase','2 hours ago','check'],['Seller application received','Bright Nest','Yesterday','store'],['Review reported','Weekend Sunglasses','Yesterday','flag'],['Order issue marked','SH-260924-5816','2 days ago','info']].map(([title,item,when,ico])=>`<div class="admin-activity-row"><span class="admin-activity-icon">${bridge.icon(ico,16)}</span><span><strong>${bridge.t(title)}</strong><small>${esc(item)} · ${bridge.t(when)}</small></span></div>`).join('');
 const alertRows=[[pendingSellers.length,'Pending seller approvals','/admin/sellers','peach'],[pendingProducts.length,'Products awaiting moderation','/admin/products','lilac'],[reported.length,'Reported reviews','/admin/reviews','rose'],[issues.length,'Order issues','/admin/orders','gold']].filter(row=>row[0]>0).map(([count,label,href,tone])=>`<a class="admin-alert-row ${tone}" href="${href}"><b>${count}</b><span>${bridge.t(label)}</span>${bridge.icon('arrow',14)}</a>`).join('');
 return `${metrics}<div class="admin-dashboard-grid"><div class="admin-dashboard-primary">${panel('Recent orders',`${table(['Order ID','Customer','Shop','Order total','Status','Date','Actions'],recentOrders,empty('No recent orders','Sample orders will appear here.'))}${pagination(recentOrders.length)}`,'admin-dashboard-orders')}<div class="admin-dashboard-lower">${panel('Recent seller registrations',registrations||empty('No seller applications','New applications will appear here.'))}${panel('Moderation activity',`<div class="admin-activity-list">${activity}</div>`)}</div></div><aside class="admin-dashboard-aside">${panel('Needs attention',alertRows?`<div class="admin-alert-list">${alertRows}</div>`:empty('All caught up','There are no open marketplace alerts.'))}${panel('Quick actions',`<div class="admin-quick-links"><a href="/admin/sellers?status=Pending">${bridge.icon('check',16)}<span>${bridge.t('Review seller applications')}</span>${bridge.icon('arrow',13)}</a><a href="/admin/products?status=Pending">${bridge.icon('bag',16)}<span>${bridge.t('Moderate products')}</span>${bridge.icon('arrow',13)}</a><a href="/admin/reviews?reported=1">${bridge.icon('flag',16)}<span>${bridge.t('Review reported feedback')}</span>${bridge.icon('arrow',13)}</a><a href="/admin/orders">${bridge.icon('cart',16)}<span>${bridge.t('Find an order')}</span>${bridge.icon('arrow',13)}</a></div>`)}</aside></div>`;
}
function usersPage(){
 const role=ui.filters.role||'',status=ui.filters.status||'',all=users();let rows=all.filter(row=>!ui.query||`${row.id} ${row.name} ${row.email}`.toLowerCase().includes(ui.query.toLowerCase())).filter(row=>(!role||row.role===role)&&(!status||row.status===status));
 rows.sort(ui.sort==='name'?(a,b)=>a.name.localeCompare(b.name):ui.sort==='oldest'?(a,b)=>a.joined.localeCompare(b.joined):(a,b)=>b.joined.localeCompare(a.joined));const page=paginate(rows);
 const items=page.rows.map(user=>`<div class="admin-table-row">${cell('User',`<span class="admin-person"><i>${esc(user.name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</i><span><strong>${esc(user.name)}</strong><small>${esc(user.id)}</small></span></span>`)}${cell('Email',esc(user.email))}${cell('Role',badge(user.role))}${cell('Status',badge(user.status))}${cell('Joined',date(user.joined))}${cell('Activity',bridge.t('{count} orders · {reviews} reviews',{count:user.orders,reviews:user.reviews}))}${cell('Actions',actionButton('detail-user',user.id,'View details','arrow'))}</div>`);
 const filters=`<label>${bridge.t('Role')}<select data-admin-filter="role">${option('','All roles',role)}${['Customer','Seller','Admin'].map(value=>option(value,value,role)).join('')}</select></label><label>${bridge.t('Status')}<select data-admin-filter="status">${option('','All statuses',status)}${['Active','Disabled','Pending'].map(value=>option(value,value,status)).join('')}</select></label>`;
 return `${sectionToolbar('Search name, email, or user ID',filters,`${option('recent','Recently joined',ui.sort)}${option('oldest','Oldest first',ui.sort)}${option('name','Name A–Z',ui.sort)}`)}${table(['User','Email','Role','Status','Joined','Activity','Actions'],items,empty('No users match','Try another search or change the filters.'))}${page.foot}`;
}
function sellersPage(){
 const status=ui.filters.status||'',all=sellers();let rows=all.filter(row=>!ui.query||`${row.id} ${row.name} ${row.email} ${row.shop}`.toLowerCase().includes(ui.query.toLowerCase())).filter(row=>!status||row.status===status);
 rows.sort(ui.sort==='shop'?(a,b)=>a.shop.localeCompare(b.shop):ui.sort==='oldest'?(a,b)=>a.joined.localeCompare(b.joined):(a,b)=>b.joined.localeCompare(a.joined));const page=paginate(rows);
 const items=page.rows.map(seller=>{const summary=sellerCounts(seller);return `<div class="admin-table-row">${cell('Shop',`<span class="admin-person"><i class="admin-store-avatar">${esc(seller.shop.slice(0,1))}</i><span><strong>${esc(seller.shop)}</strong><small>${esc(seller.id)} · ${esc(seller.name)}</small></span></span>`)}${cell('Seller',esc(seller.email))}${cell('Products',summary.products)}${cell('Orders',summary.orders)}${cell('Rating',seller.rating?`★ ${seller.rating}`:bridge.t('New shop'))}${cell('Status',badge(seller.status))}${cell('Actions',actionButton('detail-seller',seller.id,'View shop','arrow'))}</div>`;});
 const filters=`<label>${bridge.t('Approval / status')}<select data-admin-filter="status">${option('','All statuses',status)}${['Pending','Approved','Rejected','Suspended'].map(value=>option(value,value,status)).join('')}</select></label>`;
 return `${sectionToolbar('Search seller, shop, or seller ID',filters,`${option('recent','Recently joined',ui.sort)}${option('oldest','Oldest first',ui.sort)}${option('shop','Shop name A–Z',ui.sort)}`)}${table(['Shop','Seller','Products','Orders','Rating','Status','Actions'],items,empty('No sellers match','Try another search or change the approval filter.'))}${page.foot}`;
}
function productRow(product){const moderation=productState(product),availability=Number(product.stock)===0?'Out of stock':Number(product.stock)<=7?'Low stock':'In stock';return `<div class="admin-table-row">${cell('Product',`<span class="admin-product-person"><img src="${bridge.photo(product.image,80)}" alt=""><span><strong>${esc(product.name)}</strong><small>${esc(product.sku||product.id)} · ${esc(product.shop)}</small></span></span>`)}${cell('Category',bridge.t(product.category||'Uncategorized'))}${cell('Price',money(product.price))}${cell('Availability',badge(availability))}${cell('Moderation status',badge(moderation))}${cell('Updated',date(product.updatedAt||'2026-10-02'))}${cell('Actions',actionButton('detail-product',product.id,'Review listing','arrow'))}</div>`;}
function productsPage(){
 const moderation=ui.filters.moderation||'',category=ui.filters.category||'',shop=ui.filters.shop||'',availability=ui.filters.availability||'';let rows=allProducts().filter(row=>!ui.query||`${row.name} ${row.sku||''}`.toLowerCase().includes(ui.query.toLowerCase())).filter(row=>(!moderation||productState(row)===moderation)&&(!category||row.category===category)&&(!shop||row.shop===shop)&&(!availability||(Number(row.stock)===0?'Out of stock':Number(row.stock)<=7?'Low stock':'In stock')===availability));
 rows.sort(ui.sort==='price'?(a,b)=>a.price-b.price:ui.sort==='name'?(a,b)=>a.name.localeCompare(b.name):(a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));const page=paginate(rows),all=allProducts();
 const filters=`<label>${bridge.t('Category')}<select data-admin-filter="category">${option('','All categories',category)}${[...new Set(all.map(row=>row.category).filter(Boolean))].sort().map(value=>option(value,value,category)).join('')}</select></label><label>${bridge.t('Seller / shop')}<select data-admin-filter="shop">${option('','All shops',shop)}${[...new Set(all.map(row=>row.shop))].sort().map(value=>option(value,value,shop)).join('')}</select></label><label>${bridge.t('Moderation status')}<select data-admin-filter="moderation">${option('','All moderation',moderation)}${['Pending','Approved','Rejected','Archived'].map(value=>option(value,value,moderation)).join('')}</select></label><label>${bridge.t('Availability')}<select data-admin-filter="availability">${option('','All availability',availability)}${['In stock','Low stock','Out of stock'].map(value=>option(value,value,availability)).join('')}</select></label>`;
 const summary=`<div class="admin-inline-summary"><span>${bridge.t('Products in review queue')} <b>${all.filter(row=>productState(row)==='Pending').length}</b></span><span>${bridge.t('Archived listings')} <b>${all.filter(row=>productState(row)==='Archived').length}</b></span></div>`;
 return `${summary}${sectionToolbar('Search product name or SKU',filters,`${option('recent','Recently updated',ui.sort)}${option('name','Product name A–Z',ui.sort)}${option('price','Price: low to high',ui.sort)}`)}${table(['Product','Category','Price','Availability','Moderation status','Updated','Actions'],page.rows.map(productRow),empty('No products match','Try another search or adjust the moderation filters.'))}${page.foot}`;
}
function orderStatusLabel(status){return ({pending:'Pending',confirmed:'Confirmed',processing:'Processing',shipping:'Shipping',delivered:'Delivered',cancelled:'Cancelled'})[status]||status;}
function ordersPage(){
 const status=ui.filters.status||'',payment=ui.filters.payment||'',shop=ui.filters.shop||'',customer=ui.filters.customer||'',from=ui.filters.from||'',to=ui.filters.to||'';let rows=getOrders().filter(order=>{const text=[order.id,order.customer,order.shop,...order.items.map(item=>bridge.orderProduct(item)?.name||'')].join(' ').toLowerCase();return(!ui.query||text.includes(ui.query.toLowerCase()))&&(!status||order.status===status)&&(!payment||order.paymentStatus===payment)&&(!shop||order.shop===shop)&&(!customer||order.customer===customer)&&(!from||order.date>=from)&&(!to||order.date<=to);});
 rows.sort(ui.sort==='oldest'?(a,b)=>a.date.localeCompare(b.date):ui.sort==='amount-high'?(a,b)=>orderTotal(b)-orderTotal(a):ui.sort==='amount-low'?(a,b)=>orderTotal(a)-orderTotal(b):(a,b)=>b.date.localeCompare(a.date));const page=paginate(rows);
 const items=page.rows.map(order=>`<div class="admin-table-row ${order.adminIssue&&!order.issueResolved?'has-issue':''}">${cell('Order ID',`<strong>${esc(order.id)}</strong>${order.adminIssue&&!order.issueResolved?`<small class="admin-issue-mark">${bridge.icon('flag',12)} ${bridge.t('Attention')}</small>`:''}`)}${cell('Customer',esc(order.customer))}${cell('Shop',esc(order.shop))}${cell('Products',order.items.map(item=>`${esc(bridge.orderProduct(item)?.name||'Product')} × ${Number(item.qty)||1}`).join('<br>'))}${cell('Total',`<strong>${money(orderTotal(order))}</strong>`)}${cell('Payment',badge(order.paymentStatus))}${cell('Fulfillment',badge(orderStatusLabel(order.status)))}${cell('Date',date(order.date))}${cell('Actions',actionButton('detail-order',order.id,'View order','arrow'))}</div>`);
 const filters=`<label>${bridge.t('Order status')}<select data-admin-filter="status">${option('','All statuses',status)}${['pending','confirmed','processing','shipping','delivered','cancelled'].map(value=>option(value,orderStatusLabel(value),status)).join('')}</select></label><label>${bridge.t('Payment status')}<select data-admin-filter="payment">${option('','All payments',payment)}${['Paid','Pending','Refunded','Failed'].map(value=>option(value,value,payment)).join('')}</select></label><label>${bridge.t('Shop')}<select data-admin-filter="shop">${option('','All shops',shop)}${[...new Set(getOrders().map(row=>row.shop))].sort().map(value=>option(value,value,shop)).join('')}</select></label><label>${bridge.t('Customer')}<select data-admin-filter="customer">${option('','All customers',customer)}${[...new Set(getOrders().map(row=>row.customer))].sort().map(value=>option(value,value,customer)).join('')}</select></label><label class="admin-date-filter">${bridge.t('From')}<input type="date" data-admin-filter="from" value="${esc(from)}"></label><label class="admin-date-filter">${bridge.t('To')}<input type="date" data-admin-filter="to" value="${esc(to)}"></label>`;
 return `<div class="admin-inline-summary"><span>${bridge.t('Showing global marketplace orders')}</span><span>${bridge.t('Prototype actions only; no payments are processed.')}</span></div>${sectionToolbar('Search order, customer, product, or shop',filters,`${option('recent','Newest first',ui.sort)}${option('oldest','Oldest first',ui.sort)}${option('amount-high','Highest amount',ui.sort)}${option('amount-low','Lowest amount',ui.sort)}`)}${table(['Order ID','Customer','Shop','Products','Total','Payment','Fulfillment','Date','Actions'],items,empty('No orders match','Try another search, shop, or date range.'))}${page.foot}`;
}
function reviewRows(){const records=Object.values(getReviews()).filter(row=>['submitted','edited'].includes(row.status));return records.map(review=>{const product=productById(review.productId);return{...review,product:product?.name||review.productId,shop:review.shop||product?.shop||'Sunday Objects',rating:Number(review.rating)||0,moderationStatus:review.moderationStatus||'Visible'};});}
function reviewsPage(){
 const rating=ui.filters.rating||'',reported=ui.filters.reported||'',moderation=ui.filters.moderation||'';let rows=reviewRows().filter(row=>!ui.query||`${row.product} ${row.shop} ${row.customer||'ShopHub customer'} ${row.text||''}`.toLowerCase().includes(ui.query.toLowerCase())).filter(row=>(!rating||String(row.rating)===rating)&&(!reported||(reported==='Reported'?row.reported:!row.reported))&&(!moderation||row.moderationStatus===moderation));
 rows.sort(ui.sort==='rating-high'?(a,b)=>b.rating-a.rating:ui.sort==='rating-low'?(a,b)=>a.rating-b.rating:(a,b)=>(b.reviewDate||b.purchaseDate||'').localeCompare(a.reviewDate||a.purchaseDate||''));const page=paginate(rows);
 const items=page.rows.map(review=>`<div class="admin-table-row ${review.reported?'has-issue':''}">${cell('Review',`<strong>${esc(review.product)}</strong><small>${esc(review.shop)}</small>`)}${cell('Customer',esc(review.customer||'ShopHub customer'))}${cell('Rating',`<span class="admin-rating">${'★'.repeat(review.rating)}${'☆'.repeat(5-review.rating)} <b>${review.rating}.0</b></span>`)}${cell('Feedback',`<span class="admin-review-preview">${esc(review.text||'')}</span>`)}${cell('Reported',review.reported?badge('Reported'):bridge.t('No'))}${cell('Moderation status',badge(review.moderationStatus))}${cell('Date',date(review.reviewDate||review.purchaseDate))}${cell('Actions',actionButton('detail-review',review.key||`${review.orderId}::${review.productId}`,'Review details','arrow'))}</div>`);
 const filters=`<label>${bridge.t('Rating')}<select data-admin-filter="rating">${option('','All ratings',rating)}${[5,4,3,2,1].map(value=>option(String(value),`${value} ${bridge.t('stars')}`,rating)).join('')}</select></label><label>${bridge.t('Report status')}<select data-admin-filter="reported">${option('','All reviews',reported)}${option('Reported','Reported',reported)}${option('Not reported','Not reported',reported)}</select></label><label>${bridge.t('Moderation status')}<select data-admin-filter="moderation">${option('','All statuses',moderation)}${['Visible','Hidden'].map(value=>option(value,value,moderation)).join('')}</select></label>`;
 const summary=`<div class="admin-inline-summary"><span>${bridge.t('Visible reviews')} <b>${reviewRows().filter(row=>row.moderationStatus==='Visible').length}</b></span><span>${bridge.t('Reported')} <b>${reviewRows().filter(row=>row.reported).length}</b></span></div>`;
 return `${summary}${sectionToolbar('Search product, customer, shop, or review text',filters,`${option('recent','Newest first',ui.sort)}${option('rating-high','Highest rating',ui.sort)}${option('rating-low','Lowest rating',ui.sort)}`)}${table(['Product','Customer','Rating','Review','Reported','Moderation status','Date','Actions'],items,empty('No reviews match','Try another search or adjust the review filters.'))}${page.foot}`;
}
function categoriesPage(){
 const status=ui.filters.status||'';let rows=categoryRows().filter(row=>!ui.query||`${row.name} ${row.parent}`.toLowerCase().includes(ui.query.toLowerCase())).filter(row=>!status||row.status===status);rows.sort(ui.sort==='name'?(a,b)=>a.name.localeCompare(b.name):(a,b)=>a.sort-b.sort);const page=paginate(rows);
 const items=page.rows.map(row=>`<div class="admin-table-row">${cell('Category',`<strong>${esc(row.name)}</strong><small>${row.parent?bridge.t('Subcategory'):'—'}</small>`)}${cell('Parent category',row.parent?bridge.t(row.parent):bridge.t('Top level'))}${cell('Products',allProducts().filter(product=>product.category===row.name).length)}${cell('Status',badge(row.status))}${cell('Display order',row.sort)}${cell('Actions',`<div class="admin-row-actions">${actionButton('edit-category',row.id,'Edit','settings')}${actionButton(row.status==='Active'?'disable-category':'enable-category',row.id,row.status==='Active'?'Disable':'Enable',row.status==='Active'?'eye':'check')}${actionButton('delete-category',row.id,'Delete','trash','danger')}</div>`)}</div>`);
 const filters=`<label>${bridge.t('Status')}<select data-admin-filter="status">${option('','All statuses',status)}${['Active','Disabled'].map(value=>option(value,value,status)).join('')}</select></label>`;
 return `<div class="admin-section-actions"><span>${bridge.t('Parent categories and nested browse groups')}</span><button type="button" class="admin-button admin-button-primary" data-admin-action="add-category">${bridge.icon('plus',15)} ${bridge.t('Add category')}</button></div>${sectionToolbar('Search categories or parent categories',filters,`${option('order','Display order',ui.sort)}${option('name','Name A–Z',ui.sort)}`)}${table(['Category','Parent category','Products','Status','Display order','Actions'],page.rows.map(row=>items.find(item=>item.includes(`data-id="${row.id}"`))||''),empty('No categories match','Try another search or add a marketplace category.'))}${page.foot}`;
}
function orderDetails(order){
 const timeline=['pending','confirmed','processing','shipping','delivered'],current=timeline.indexOf(order.status),cancelled=order.status==='cancelled';
 return `<div class="admin-detail-layout"><div class="admin-detail-main">${panel('Order items',`<div class="admin-detail-items">${order.items.map(item=>{const product=bridge.orderProduct(item);return `<a class="admin-detail-item" href="/products/${encodeURIComponent(item.id)}"><img src="${bridge.photo(product.image,110)}" alt=""><span><strong>${esc(product.name)}</strong><small>${esc(item.variant||product.color||'Standard')} · ${bridge.t('Quantity')} ${Number(item.qty)||1}</small></span><b>${money(product.price*(Number(item.qty)||1))}</b></a>`;}).join('')}</div><div class="admin-detail-total"><span>${bridge.t('Order total')}</span><strong>${money(orderTotal(order))}</strong></div>`)}${panel('Fulfillment timeline',`<ol class="admin-timeline ${cancelled?'is-cancelled':''}">${(cancelled?['pending','cancelled']:timeline).map((status,index)=>`<li class="${cancelled||index<=current?'is-complete':''}"><i></i><span><strong>${bridge.t(orderStatusLabel(status))}</strong><small>${index===0?date(order.date):index<=current?bridge.t('Sample status update'):bridge.t('Awaiting update')}</small></span></li>`).join('')}</ol>`)}</div><aside class="admin-detail-aside">${panel('Customer',`<strong>${esc(order.customer)}</strong><small>${bridge.t('Customer order reference')}: <a href="/orders/${encodeURIComponent(order.id)}">${esc(order.id)}</a></small>`)}${panel('Shop & shipping',`<strong>${esc(order.shop)}</strong><small>${bridge.t(order.shipping.method)} · ${money(order.shipping.fee)}</small><small>${esc(order.shipping.address)}</small>`)}${panel('Payment information',`<div class="admin-detail-kv"><span>${bridge.t('Payment status')}</span>${badge(order.paymentStatus)}</div><div class="admin-detail-kv"><span>${bridge.t('Payment method')}</span><strong>${bridge.t(order.paymentMethod)}</strong></div><p class="admin-sample-caption">${bridge.t('Sample payment record. No payment was processed.')}</p>`)}</aside></div><div class="admin-detail-actions">${order.adminIssue&&!order.issueResolved?`<button class="admin-button admin-button-quiet" data-admin-action="resolve-issue" data-id="${esc(order.id)}">${bridge.icon('check',15)} ${bridge.t('Resolve issue')}</button>`:`<button class="admin-button admin-button-quiet" data-admin-action="mark-issue" data-id="${esc(order.id)}">${bridge.icon('flag',15)} ${bridge.t('Mark order issue')}</button>`}<button class="admin-button admin-button-quiet" data-admin-action="mock-refund" data-id="${esc(order.id)}" ${order.paymentStatus==='Refunded'?'disabled':''}>${bridge.icon('card',15)} ${bridge.t('Mark mock refund')}</button>${['cancelled','delivered'].includes(order.status)?'':`<button class="admin-button admin-button-danger" data-admin-action="cancel-order" data-id="${esc(order.id)}">${bridge.icon('close',15)} ${bridge.t('Cancel order')}</button>`}</div>${order.adminIssue?`<p class="admin-issue-note"><b>${bridge.t('Issue note')}:</b> ${esc(order.adminIssue)} ${order.issueResolved?`· ${bridge.t('Resolved')}`:''}</p>`:''}`;
}
function detailContent(){
 const detail=ui.detail;if(!detail)return'';const close=`<button type="button" class="admin-modal-close" data-admin-action="close-detail" aria-label="${bridge.t('Close')}">${bridge.icon('close',17)}</button>`;
 if(detail.type==='user'){
  const user=users().find(row=>row.id===detail.id);if(!user)return'';const form=detail.edit?`<form id="admin-user-form"><label>${bridge.t('Full name')}<input name="name" required maxlength="80" value="${esc(user.name)}"></label><label>${bridge.t('Email')}<input name="email" type="email" required value="${esc(user.email)}"></label><div class="admin-modal-actions"><button type="button" class="admin-button admin-button-quiet" data-admin-action="cancel-user-edit">${bridge.t('Cancel')}</button><button class="admin-button admin-button-primary">${bridge.t('Save changes')}</button></div></form>`:`<div class="admin-detail-kv"><span>${bridge.t('Email')}</span><strong>${esc(user.email)}</strong></div><div class="admin-detail-kv"><span>${bridge.t('Role')}</span>${badge(user.role)}</div><div class="admin-detail-kv"><span>${bridge.t('Status')}</span>${badge(user.status)}</div><div class="admin-detail-kv"><span>${bridge.t('Joined')}</span><strong>${date(user.joined)}</strong></div><div class="admin-user-summary"><span><b>${user.orders}</b>${bridge.t('Orders')}</span><span><b>${user.wishlist}</b>${bridge.t('Wishlist')}</span><span><b>${user.reviews}</b>${bridge.t('Reviews')}</span></div><div class="admin-modal-actions"><button class="admin-button admin-button-quiet" data-admin-action="edit-user" data-id="${esc(user.id)}">${bridge.icon('settings',15)} ${bridge.t('Edit profile')}</button><button class="admin-button ${user.status==='Active'?'admin-button-danger':'admin-button-primary'}" data-admin-action="toggle-user" data-id="${esc(user.id)}">${bridge.t(user.status==='Active'?'Disable account':'Enable account')}</button></div>`;
  return `<section class="admin-modal" role="dialog" aria-modal="true" aria-labelledby="admin-modal-title">${close}<p class="admin-eyebrow">${bridge.t('USER PROFILE')}</p><h2 id="admin-modal-title">${esc(user.name)}</h2><p class="admin-modal-lead">${esc(user.id)}</p>${form}</section>`;
 }
 if(detail.type==='seller'){
  const seller=sellers().find(row=>row.id===detail.id);if(!seller)return'';const summary=sellerCounts(seller),products=allProducts().filter(row=>row.shop===seller.shop).slice(0,4);return `<section class="admin-modal admin-modal-wide" role="dialog" aria-modal="true" aria-labelledby="admin-modal-title">${close}<p class="admin-eyebrow">${bridge.t('SELLER PROFILE')}</p><div class="admin-modal-heading-flex"><div><h2 id="admin-modal-title">${esc(seller.shop)}</h2><p class="admin-modal-lead">${esc(seller.name)} · ${esc(seller.id)}</p></div>${badge(seller.status)}</div><p class="admin-seller-description">${esc(seller.description)}</p><div class="admin-detail-kv"><span>${bridge.t('Contact')}</span><strong>${esc(seller.email)}</strong></div><div class="admin-detail-kv"><span>${bridge.t('Application date')}</span><strong>${date(seller.joined)}</strong></div><div class="admin-user-summary"><span><b>${summary.products}</b>${bridge.t('Products')}</span><span><b>${summary.orders}</b>${bridge.t('Orders')}</span><span><b>${summary.reviews}</b>${bridge.t('Reviews')}</span></div>${panel('Shop products',products.length?`<div class="admin-compact-products">${products.map(row=>`<span><b>${esc(row.name)}</b><small>${bridge.t(productState(row))} · ${money(row.price)}</small></span>`).join('')}</div>`:empty('No shop products','This shop does not have sample listings yet.'))}<div class="admin-modal-actions">${seller.status==='Pending'?`<button class="admin-button admin-button-primary" data-admin-action="approve-seller" data-id="${esc(seller.id)}">${bridge.icon('check',15)} ${bridge.t('Approve seller')}</button><button class="admin-button admin-button-danger" data-admin-action="reject-seller" data-id="${esc(seller.id)}">${bridge.icon('close',15)} ${bridge.t('Reject application')}</button>`:seller.status==='Approved'?`<button class="admin-button admin-button-danger" data-admin-action="suspend-seller" data-id="${esc(seller.id)}">${bridge.t('Suspend seller')}</button>`:`<button class="admin-button admin-button-primary" data-admin-action="restore-seller" data-id="${esc(seller.id)}">${bridge.t('Restore seller')}</button>`}</div></section>`;
 }
 if(detail.type==='product'){
  const product=productById(detail.id);if(!product)return'';const status=productState(product),managed=bridge.readSellerManagedProducts().some(row=>row.id===product.id);return `<section class="admin-modal admin-modal-wide" role="dialog" aria-modal="true" aria-labelledby="admin-modal-title">${close}<p class="admin-eyebrow">${bridge.t('PRODUCT MODERATION')}</p><div class="admin-modal-product-head"><img src="${bridge.photo(product.image,300)}" alt=""><div><h2 id="admin-modal-title">${esc(product.name)}</h2><p>${esc(product.sku||product.id)} · <a href="/products/${encodeURIComponent(product.id)}">${bridge.t('Customer product page')} ${bridge.icon('arrow',12)}</a></p>${badge(status)}</div></div><p class="admin-seller-description">${esc(product.detail||product.description||'')}</p><div class="admin-detail-kv"><span>${bridge.t('Seller / shop')}</span><strong>${esc(product.shop)}</strong></div><div class="admin-detail-kv"><span>${bridge.t('Category')}</span><strong>${bridge.t(product.category)}</strong></div><div class="admin-detail-kv"><span>${bridge.t('Price')} · ${bridge.t('Availability')}</span><strong>${money(product.price)} · ${Number(product.stock)||0} ${bridge.t('units')}</strong></div>${detail.reason?`<p class="admin-issue-note"><b>${bridge.t('Moderation reason')}:</b> ${esc(detail.reason)}</p>`:''}<div class="admin-modal-actions">${status==='Pending'?`<button class="admin-button admin-button-primary" data-admin-action="approve-product" data-id="${esc(product.id)}">${bridge.t('Approve product')}</button><button class="admin-button admin-button-danger" data-admin-action="reject-product" data-id="${esc(product.id)}">${bridge.t('Reject with reason')}</button>`:status==='Archived'||status==='Rejected'?`<button class="admin-button admin-button-primary" data-admin-action="restore-product" data-id="${esc(product.id)}">${bridge.t('Restore product')}</button>`:`<button class="admin-button admin-button-danger" data-admin-action="archive-product" data-id="${esc(product.id)}">${bridge.t('Archive product')}</button>`}${managed?`<a class="admin-button admin-button-quiet" href="/seller/products">${bridge.t('Open seller product list')} ${bridge.icon('arrow',13)}</a>`:''}<button class="admin-button admin-button-quiet" data-admin-action="feature-product" data-id="${esc(product.id)}">${product.featured?bridge.t('Remove highlight'):bridge.t('Feature product')}</button></div></section>`;
 }
 if(detail.type==='order'){const order=getOrders().find(row=>row.id===detail.id);return order?`<section class="admin-modal admin-modal-wide" role="dialog" aria-modal="true" aria-labelledby="admin-modal-title">${close}<p class="admin-eyebrow">${bridge.t('GLOBAL ORDER')}</p><div class="admin-modal-heading-flex"><div><h2 id="admin-modal-title">${esc(order.id)}</h2><p class="admin-modal-lead">${date(order.date)} · ${esc(order.customer)}</p></div>${badge(orderStatusLabel(order.status))}</div>${orderDetails(order)}</section>`:'';}
 if(detail.type==='review'){
  const review=getReviews()[detail.id];if(!review)return'';const product=productById(review.productId);return `<section class="admin-modal admin-modal-wide" role="dialog" aria-modal="true" aria-labelledby="admin-modal-title">${close}<p class="admin-eyebrow">${bridge.t('REVIEW MODERATION')}</p><h2 id="admin-modal-title">${esc(product?.name||review.productId)}</h2><p class="admin-modal-lead">${esc(review.customer||'ShopHub customer')} · ${esc(review.shop||product?.shop||'')} · ${date(review.reviewDate||review.purchaseDate)}</p><div class="admin-review-rating-large">${'★'.repeat(Number(review.rating)||0)}${'☆'.repeat(5-(Number(review.rating)||0))} <b>${Number(review.rating)||0}.0</b></div><h3>${esc(review.title||bridge.t('Customer review'))}</h3><p class="admin-review-full">${esc(review.text||'')}</p>${review.sellerResponse?`<div class="admin-seller-reply"><b>${bridge.t('Seller response')}</b><p>${esc(review.sellerResponse)}</p></div>`:''}${review.reported?`<p class="admin-issue-note">${bridge.icon('flag',14)} ${bridge.t('Reported')}: ${esc(review.reportReason||bridge.t('Reported feedback needs review.'))}</p>`:''}<div class="admin-detail-kv"><span>${bridge.t('Moderation status')}</span>${badge(review.moderationStatus||'Visible')}</div><div class="admin-modal-actions">${review.moderationStatus==='Hidden'?`<button class="admin-button admin-button-primary" data-admin-action="restore-review" data-id="${esc(detail.id)}">${bridge.t('Restore review')}</button>`:`<button class="admin-button admin-button-quiet" data-admin-action="hide-review" data-id="${esc(detail.id)}">${bridge.t('Hide review')}</button>`}<button class="admin-button admin-button-danger" data-admin-action="delete-review" data-id="${esc(detail.id)}">${bridge.t('Delete review')}</button></div><p class="admin-sample-caption">${bridge.t('Moderation changes are reflected in the customer and seller review displays.')}</p></section>`;
 }
 return categoryModal(detail);
}
function categoryModal(detail){
 const existing=detail.id?categoryRows().find(row=>row.id===detail.id):null,parents=categoryRows().filter(row=>!row.parent&&row.status==='Active'&&row.id!==detail.id),row=existing||{name:'',parent:'',status:'Active',sort:categoryRows().length+1,description:''};
 return `<section class="admin-modal" role="dialog" aria-modal="true" aria-labelledby="admin-modal-title"><button type="button" class="admin-modal-close" data-admin-action="close-detail" aria-label="${bridge.t('Close')}">${bridge.icon('close',17)}</button><p class="admin-eyebrow">${bridge.t('CATEGORY SETTINGS')}</p><h2 id="admin-modal-title">${bridge.t(existing?'Edit category':'Add category')}</h2><form id="admin-category-form" data-id="${esc(existing?.id||'')}"><label>${bridge.t('Category name')}<input name="name" required maxlength="60" value="${esc(row.name)}" data-modal-autofocus></label><label>${bridge.t('Parent category')}<select name="parent"><option value="">${bridge.t('Top level')}</option>${parents.map(parent=>`<option value="${esc(parent.name)}" ${parent.name===row.parent?'selected':''}>${esc(parent.name)}</option>`).join('')}</select></label><label>${bridge.t('Description')}<textarea name="description" rows="3" maxlength="180">${esc(row.description)}</textarea></label><label>${bridge.t('Display order')}<input name="sort" type="number" min="1" required value="${Number(row.sort)||1}"></label><p class="admin-form-error" id="admin-category-error" hidden></p><div class="admin-modal-actions"><button type="button" class="admin-button admin-button-quiet" data-admin-action="close-detail">${bridge.t('Cancel')}</button><button class="admin-button admin-button-primary">${bridge.t('Save category')}</button></div></form></section>`;
}
function modalMarkup(){return ui.detail?`<div class="admin-modal-backdrop" data-admin-backdrop>${detailContent()}</div>`:'';}
function showToast(message){const region=document.querySelector('#toast-region');if(!region)return;region.textContent=bridge.t(message);region.classList.add('is-visible');clearTimeout(ui.toastTimer);ui.toastTimer=setTimeout(()=>region.classList.remove('is-visible'),2600);}
function syncCustomerCategories(){const records=categoryRows(),active=records.filter(row=>!row.parent&&row.status==='Active');for(let i=bridge.categories.length-1;i>=0;i--){if(!active.some(row=>row.name===bridge.categories[i][0]))bridge.categories.splice(i,1);}active.forEach(row=>{if(!bridge.categories.some(entry=>entry[0]===row.name))bridge.categories.push([row.name,row.description||`Discover ${row.name.toLowerCase()}`, 'photo-1600210492486-724fe5c67fb0','home']);});}
function openDetail(type,id,extra={}){ui.detail={type,id,...extra};render();document.querySelector('[data-modal-autofocus]')?.focus();}
function setSellerStatus(id,status,reason=''){const rows=sellers(),seller=rows.find(row=>row.id===id);if(!seller)return;seller.status=status;if(reason)seller.reason=reason;write(K.sellers,rows);const account=users().find(row=>row.id===id);if(account){const accountRows=users(),user=accountRows.find(row=>row.id===id);user.status=status==='Approved'?'Active':status==='Pending'?'Pending':status==='Rejected'?'Disabled':'Disabled';write(K.users,accountRows);}return seller;}
function changeProduct(id,status,reason=''){const states=productStates();states[id]={...(states[id]||{}),moderation:status,...(reason?{reason}:{})};saveProductStates(states);const managed=bridge.readSellerManagedProducts(),row=managed.find(product=>product.id===id);if(row){row.status=status==='Approved'?'Active':status==='Pending'?'Draft':'Archived';bridge.writeSellerManagedProducts(managed);bridge.syncSellerMarketplaceCatalog();}return states[id];}
function updateOrder(id,mutate){const rows=getOrders(),order=rows.find(row=>row.id===id);if(!order)return;mutate(order);saveOrders(rows);}
function handleAction(action,id){
 if(action==='close-detail'){ui.detail=null;render();return;}if(action==='add-category'){openDetail('category');return;}
 if(action==='detail-user'||action==='detail-seller'||action==='detail-product'||action==='detail-order'||action==='detail-review'){openDetail(action.replace('detail-',''),id);return;}
 if(action==='edit-user'){ui.detail={type:'user',id,edit:true};render();return;}if(action==='cancel-user-edit'){ui.detail.edit=false;render();return;}
 if(action==='toggle-user'){const row=users().find(user=>user.id===id);if(!row||!window.confirm(bridge.t(row.status==='Active'?'Disable this account?':'Enable this account?')))return;const rows=users(),user=rows.find(item=>item.id===id);user.status=user.status==='Active'?'Disabled':'Active';write(K.users,rows);ui.detail={type:'user',id};render();showToast('Account status updated');return;}
 if(action==='approve-seller'){setSellerStatus(id,'Approved');ui.detail={type:'seller',id};render();showToast('Seller approved');return;}
 if(action==='reject-seller'){const reason=window.prompt(bridge.t('Enter a reason for rejection'));if(reason===null)return;if(reason.trim().length<8){showToast('Please enter a reason of at least 8 characters');return;}if(!window.confirm(bridge.t('Reject this seller application?')))return;setSellerStatus(id,'Rejected',reason.trim());ui.detail={type:'seller',id};render();showToast('Seller application rejected');return;}
 if(action==='suspend-seller'||action==='restore-seller'){const status=action==='suspend-seller'?'Suspended':'Approved';if(!window.confirm(bridge.t(status==='Suspended'?'Suspend this seller and shop?':'Restore this seller and shop?')))return;setSellerStatus(id,status);ui.detail={type:'seller',id};render();showToast('Seller status updated');return;}
 if(action==='approve-product'){changeProduct(id,'Approved');ui.detail={type:'product',id};render();showToast('Product approved');return;}
 if(action==='reject-product'){const reason=window.prompt(bridge.t('Enter a reason for rejection'));if(reason===null)return;if(reason.trim().length<8){showToast('Please enter a reason of at least 8 characters');return;}if(!window.confirm(bridge.t('Reject this product listing?')))return;changeProduct(id,'Rejected',reason.trim());ui.detail={type:'product',id,reason:reason.trim()};render();showToast('Product rejected');return;}
 if(action==='archive-product'){if(!window.confirm(bridge.t('Archive this product listing?')))return;changeProduct(id,'Archived');ui.detail={type:'product',id};render();showToast('Product archived');return;}
 if(action==='restore-product'){changeProduct(id,'Approved');ui.detail={type:'product',id};render();showToast('Product restored');return;}
 if(action==='feature-product'){const states=productStates();states[id]={...(states[id]||{}),featured:!states[id]?.featured};saveProductStates(states);ui.detail={type:'product',id};render();showToast('Product highlight updated');return;}
 if(action==='cancel-order'){if(!window.confirm(bridge.t('Cancel this order? This is a mock administrative action.')))return;updateOrder(id,order=>{order.status='cancelled';order.cancelledAt=new Date().toISOString();order.updatedAt=new Date().toISOString().slice(0,10);});ui.detail={type:'order',id};render();showToast('Order cancelled in this prototype');return;}
 if(action==='mark-issue'){const reason=window.prompt(bridge.t('Add a short note about this order issue'));if(reason===null)return;if(reason.trim().length<5){showToast('Please enter an issue note');return;}updateOrder(id,order=>{order.adminIssue=reason.trim();order.issueResolved=false;});ui.detail={type:'order',id};render();showToast('Order issue marked');return;}
 if(action==='resolve-issue'){if(!window.confirm(bridge.t('Resolve this order issue?')))return;updateOrder(id,order=>{order.issueResolved=true;order.updatedAt=new Date().toISOString().slice(0,10);});ui.detail={type:'order',id};render();showToast('Order issue resolved');return;}
 if(action==='mock-refund'){if(!window.confirm(bridge.t('Mark this sample payment as refunded? No payment provider will be contacted.')))return;updateOrder(id,order=>{order.paymentStatus='Refunded';order.mockRefund=true;order.updatedAt=new Date().toISOString().slice(0,10);});ui.detail={type:'order',id};render();showToast('Sample refund status updated');return;}
 if(action==='hide-review'||action==='restore-review'){const rows=getReviews(),review=rows[id];if(!review)return;if(action==='hide-review'&&!window.confirm(bridge.t('Hide this review from customer product pages?')))return;review.moderationStatus=action==='hide-review'?'Hidden':'Visible';review.moderationHistory=[...(review.moderationHistory||[]),{action:review.moderationStatus,at:new Date().toISOString()}];saveReviews(rows);ui.detail={type:'review',id};render();showToast('Review moderation updated');return;}
 if(action==='delete-review'){if(!window.confirm(bridge.t('Delete this review from the prototype? This cannot be undone.')))return;const rows=getReviews();if(rows[id]){rows[id].status='deleted';rows[id].moderationStatus='Deleted';rows[id].moderationHistory=[...(rows[id].moderationHistory||[]),{action:'Deleted',at:new Date().toISOString()}];saveReviews(rows);}ui.detail=null;render();showToast('Review deleted');return;}
 if(['edit-category'].includes(action)){openDetail('category',id);return;}
 if(action==='disable-category'||action==='enable-category'){const rows=categoryRows(),row=rows.find(item=>item.id===id);if(!row)return;const status=action==='disable-category'?'Disabled':'Active';if(!window.confirm(bridge.t(status==='Disabled'?'Disable this category?':'Enable this category?')))return;row.status=status;write(K.categories,rows);syncCustomerCategories();refresh(true);showToast('Category status updated');return;}
 if(action==='delete-category'){const row=categoryRows().find(item=>item.id===id);if(!row)return;if(!window.confirm(bridge.t('Delete this category? Products in it will become uncategorized.')))return;deleteCategory(id);refresh();showToast('Category deleted');return;}
}
function deleteCategory(id){const rows=categoryRows(),row=rows.find(item=>item.id===id);if(!row)return;const name=row.name,names=[name,...rows.filter(item=>item.parent===name).map(item=>item.name)];const products=bridge.readSellerManagedProducts();products.forEach(product=>{if(names.includes(product.category))product.category='Uncategorized';});bridge.writeSellerManagedProducts(products);bridge.products.forEach(product=>{if(names.includes(product.category))product.category='Uncategorized';});write(K.categories,rows.filter(item=>item.id!==id&&item.parent!==name));syncCustomerCategories();}
function onUserSubmit(form){if(!form.reportValidity())return;const rows=users(),user=rows.find(row=>row.id===ui.detail?.id);if(!user)return;const values=Object.fromEntries(new FormData(form));user.name=values.name.trim();user.email=values.email.trim();write(K.users,rows);ui.detail.edit=false;render();showToast('User profile saved');}
function onCategorySubmit(form){if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form)),rows=categoryRows(),editing=rows.find(row=>row.id===form.dataset.id),name=values.name.trim(),normalized=name.toLocaleLowerCase();if(rows.some(row=>row.id!==editing?.id&&row.name.toLocaleLowerCase()===normalized)){const error=document.querySelector('#admin-category-error');error.textContent=bridge.t('A category with this name already exists.');error.hidden=false;return;}if(values.parent&&values.parent===name){const error=document.querySelector('#admin-category-error');error.textContent=bridge.t('A category cannot be its own parent.');error.hidden=false;return;}const row=editing||{id:`cat-${Date.now()}`,status:'Active'};const oldName=row.name;Object.assign(row,{name,parent:values.parent,description:values.description.trim(),sort:Number(values.sort)||rows.length+1});if(!editing)rows.push(row);write(K.categories,rows);if(oldName&&oldName!==name){rows.forEach(item=>{if(item.parent===oldName)item.parent=name;});bridge.products.forEach(product=>{if(product.category===oldName)product.category=name;});const managed=bridge.readSellerManagedProducts();managed.forEach(product=>{if(product.category===oldName)product.category=name;});bridge.writeSellerManagedProducts(managed);}syncCustomerCategories();ui.detail=null;refresh();showToast('Category saved');}
function wireModalFocus(){if(!ui.detail)return;const dialog=document.querySelector('.admin-modal');dialog?.setAttribute('tabindex','-1');dialog?.focus({preventScroll:true});}
export function mountAdminPortal(shared){
 bridge=shared;const section=location.pathname.split('/').filter(Boolean)[1]||'dashboard';ui.section=({users:'users',sellers:'sellers',products:'products',orders:'orders',reviews:'reviews',categories:'categories'})[section]||'dashboard';const params=new URLSearchParams(location.search);ui.filters={};for(const key of ['status','reported'])if(params.has(key))ui.filters[key]=key==='reported'?'Reported':params.get(key);ui.query='';ui.page=1;ui.sort=ui.section==='users'||ui.section==='sellers'?'recent':ui.section==='categories'?'order':'recent';render();
 document.addEventListener('click',event=>{
  const page=event.target.closest('[data-admin-page]');if(page){const next=Number(page.dataset.adminPage);if(next<1||page.disabled)return;ui.page=next;refresh();return;}
  const action=event.target.closest('[data-admin-action]');if(action){handleAction(action.dataset.adminAction,action.dataset.id);return;}
  if(event.target.matches('[data-admin-backdrop]')){ui.detail=null;render();}
 });
 document.addEventListener('input',event=>{if(event.target.id==='admin-search'){ui.query=event.target.value;ui.page=1;refresh(true);}});
 document.addEventListener('change',event=>{
  if(event.target.matches('[data-admin-filter]')){ui.filters[event.target.dataset.adminFilter]=event.target.value;ui.page=1;refresh();}
  if(event.target.id==='admin-sort'){ui.sort=event.target.value;ui.page=1;refresh();}
 });
 document.addEventListener('submit',event=>{
  if(event.target.id==='admin-user-form'){event.preventDefault();onUserSubmit(event.target);}
  if(event.target.id==='admin-category-form'){event.preventDefault();onCategorySubmit(event.target);}
 });
 document.addEventListener('keydown',event=>{
  if(event.key==='Escape'&&ui.detail){ui.detail=null;render();return;}
  if(event.key!=='Tab'||!ui.detail)return;const dialog=document.querySelector('.admin-modal');if(!dialog)return;const focusable=[...dialog.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}
 });
}
