import { icon } from '../src/components.js';

const products = [
  { id: 'studio-headphones', name: 'Studio Wireless Headphones', category: 'Tech & audio', shop: 'North & Tone', price: 89, old: 119, rating: '4.9', reviews: 248, flag: 'Bestseller', color: 'Sand', image: 'photo-1505740420928-5e560c06d30e', alt: 'Warm tan wireless headphones on a pale background', detail: 'Thoughtful sound for everywhere. These beautifully balanced wireless headphones pair soft memory-foam cushions with 40 hours of listening time, so the soundtrack goes as far as you do.', specs: [['Listening time','Up to 40 hours'],['Connection','Bluetooth 5.3'],['Finish','Sandstone'],['Warranty','2 years']] },
  { id: 'everyday-tote', name: 'Everyday Leather Tote', category: 'Accessories', shop: 'Marlow Goods', price: 64, old: 78, rating: '4.8', reviews: 182, flag: 'Small-batch made', color: 'Cognac', image: 'photo-1548036328-c9fa89d128fa', alt: 'Sculptural cognac leather handbag', detail: 'An easy, everyday carryall crafted from responsibly sourced leather. Room for your laptop, lunch and all the little things, with an inside pocket that keeps your keys right where they belong.', specs: [['Material','Responsibly sourced leather'],['Dimensions','14 × 11 × 5 in'],['Made in','Portland, Oregon'],['Care','Leather balm']] },
  { id: 'cloud-runner', name: 'Cloud Knit Runner', category: 'Shoes', shop: 'Common Ground', price: 78, old: 96, rating: '4.7', reviews: 96, flag: '18% off', color: 'Chalk', image: 'photo-1542291026-7eec264c27ff', alt: 'Sleek coral and white running shoe', detail: 'A feather-light knit upper and springy recycled foam make this your new just-one-more-block shoe. Made to move comfortably from weekday errands to weekend miles.', specs: [['Upper','Recycled knit'],['Sole','Rebound foam'],['Fit','True to size'],['Care','Cold hand wash']] },
  { id: 'ceramic-vase', name: 'Sunday Ceramic Vase', category: 'Home & living', shop: 'Sunday Objects', price: 48, old: 0, rating: '4.9', reviews: 71, flag: 'Hand finished', color: 'Oat', image: 'photo-1578500494198-246f612d3b3d', alt: 'Hand-shaped cream ceramic vase', detail: 'A little sculptural moment for the windowsill. Each stoneware vase is thrown and glazed by hand, so no two have quite the same softly speckled finish.', specs: [['Material','Stoneware'],['Height','8.5 in'],['Made in','Hudson Valley, NY'],['Finish','Food-safe glaze']] },
  { id: 'table-lamp', name: 'Modern Table Lamp', category: 'Home & living', shop: 'Sunday Objects', price: 52, old: 68, rating: '4.8', reviews: 133, flag: 'A customer favorite', color: 'Warm white', image: 'photo-1507473885765-e6ed057f782c', alt: 'Warm ambient table lamp in a serene room', detail: 'A softly glowing little companion for your bedside or favorite reading corner. The linen shade diffuses warm light, while the ceramic base feels lovely to the touch.', specs: [['Material','Ceramic, linen'],['Height','16 in'],['Bulb','E26 LED included'],['Cord','6 ft, braided']] },
  { id: 'canvas-sneaker', name: 'Daily Canvas Sneaker', category: 'Shoes', shop: 'Common Ground', price: 68, old: 0, rating: '4.6', reviews: 54, flag: 'Easy essential', color: 'Cloud', image: 'photo-1525966222134-fcfa99b8ae77', alt: 'White low-top canvas sneakers', detail: 'The pair you reach for without thinking. Organic cotton canvas, a flexible rubber sole and a removable footbed make everyday comfort feel effortless.', specs: [['Upper','Organic cotton'],['Sole','Natural rubber'],['Fit','True to size'],['Care','Spot clean']] },
  { id: 'linen-throw', name: 'Soft Linen Throw', category: 'Home & living', shop: 'Wilder Home', price: 82, old: 104, rating: '4.8', reviews: 88, flag: '21% off', color: 'Sage', image: 'photo-1600210492486-724fe5c67fb0', alt: 'Sage green linen throw draped over a sofa', detail: 'European flax linen, softened by a wash and made for slow mornings. Light enough for summer evenings and just right layered over your favorite chair.', specs: [['Material','100% European flax'],['Size','55 × 75 in'],['Made in','Lisbon, Portugal'],['Care','Machine wash cold']] },
  { id: 'weekend-sunglasses', name: 'Weekend Sunglasses', category: 'Accessories', shop: 'Kindred Supply', price: 42, old: 0, rating: '4.7', reviews: 62, flag: 'Sunny day staple', color: 'Tortoise', image: 'photo-1511499767150-a48a237f0083', alt: 'Tortoiseshell sunglasses in natural light', detail: 'A classic shape with a comfortably light feel. These everyday frames have polarized lenses and come with a recycled-fabric pouch for the days you leave them in your bag.', specs: [['Frame','Plant-based acetate'],['Lens','Polarized UV400'],['Fit','Medium'],['Included','Recycled pouch']] },
  { id: 'pour-over-set', name: 'Slow Morning Pour-over Set', category: 'Home & living', shop: 'Sunday Objects', price: 56, old: 72, rating: '4.9', reviews: 104, flag: 'Hand finished', color: 'Ivory', image: 'photo-1495474472287-4d71bcdd2085', alt: 'Ceramic pour-over coffee set on a wood counter', detail: 'For coffee worth taking your time over. The reusable ceramic dripper and matching cup are finished by hand and sized for a quietly excellent one-cup ritual.', specs: [['Includes','Dripper + 12 oz cup'],['Material','Glazed stoneware'],['Dishwasher','Safe'],['Made in','Hudson Valley, NY']] },
  { id: 'leather-wallet', name: 'Pocket-sized Leather Wallet', category: 'Accessories', shop: 'Marlow Goods', price: 39, old: 0, rating: '4.8', reviews: 119, flag: 'Made to last', color: 'Chestnut', image: 'photo-1627123424574-724758594e93', alt: 'Minimal brown leather card holder wallet', detail: 'A streamlined home for the essentials, cut and stitched in a small workshop. The vegetable-tanned leather develops a rich, personal patina over time.', specs: [['Material','Vegetable-tanned leather'],['Capacity','6 cards + folded bills'],['Made in','Portland, Oregon'],['Care','Leather conditioner']] },
  { id: 'bloom-bottle', name: 'Everyday Glass Bottle', category: 'Outdoors', shop: 'Kindred Supply', price: 34, old: 0, rating: '4.6', reviews: 41, flag: 'Refill, repeat', color: 'Clear / moss', image: 'photo-1602143407151-7111542de6e8', alt: 'Reusable clear drinking bottle with green detail', detail: 'A simple refillable bottle with a satisfying feel in the hand. Durable borosilicate glass, a protective silicone sleeve and a leak-resistant bamboo lid go wherever you do.', specs: [['Capacity','20 oz'],['Glass','Borosilicate'],['Lid','Bamboo + silicone seal'],['Dishwasher','Glass body only']] },
  { id: 'wireless-speaker', name: 'Little Room Speaker', category: 'Tech & audio', shop: 'North & Tone', price: 72, old: 92, rating: '4.7', reviews: 83, flag: '22% off', color: 'Forest', image: 'photo-1608043152269-423dbba4e7e1', alt: 'Compact portable wireless speaker', detail: 'Small footprint, wonderfully full sound. The splash-resistant shell and 18-hour battery make it equally at home on the bookshelf and out in the garden.', specs: [['Battery','18 hours'],['Connection','Bluetooth 5.2'],['Water rating','IPX5'],['Shell','Recycled fabric']] },
];

const categories = [
  ['Home & living', 'Spaces for slower mornings', 'photo-1600210492486-724fe5c67fb0', 'home'],
  ['Accessories', 'Little details, big joy', 'photo-1548036328-c9fa89d128fa', 'bag'],
  ['Shoes', 'Made for your every day', 'photo-1525966222134-fcfa99b8ae77', 'sparkle'],
  ['Tech & audio', 'Sound good, feel good', 'photo-1505740420928-5e560c06d30e', 'sparkle'],
  ['Outdoors', 'Take the good outside', 'photo-1470770841072-f978cf4d019e', 'sparkle'],
];
const dollars = (n) => `$${n.toFixed(2)}`;
const photo = (id, width = 760) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const card = (p) => `<article class="product-card"><a class="product-image" href="/products/${p.id}" aria-label="View ${p.name}"><img src="${photo(p.image)}" alt="${p.alt}" loading="lazy"><span class="product-flag">${p.flag}</span></a><button class="save-button" type="button" data-action="save" data-name="${p.name}" aria-label="Save ${p.name}" aria-pressed="false">${icon('heart',18)}</button><div class="product-info"><a href="/products/${p.id}" class="product-title">${p.name}</a><a class="product-shop" href="/products?shop=${encodeURIComponent(p.shop)}">${p.shop} <span aria-label="Verified shop">✓</span></a><div class="price-row"><span class="price">${dollars(p.price)}</span>${p.old ? `<s>${dollars(p.old)}</s>` : ''}<span class="rating">${icon('star',14)} ${p.rating}</span></div><button class="quick-add" type="button" data-action="add" data-name="${p.name}">${icon('plus',16)} Add to bag</button></div></article>`;

function header(active = '') {
  return `<div class="announcement">A little more good in your everyday <span>Free shipping over $75</span></div><header class="market-header"><div class="header-main"><button class="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false" data-action="menu">${icon('menu',22)}</button><a class="brand" href="/" aria-label="ShopHub home"><span class="brand-mark"><i></i><i></i><i></i><i></i></span><span>shop<span class="brand-accent">hub</span><span class="brand-period">.</span></span></a><nav class="primary-nav" aria-label="Main navigation"><a class="${active === 'home' ? 'active' : ''}" href="/">Discover</a><a class="${active === 'products' ? 'active' : ''}" href="/products">Shop all</a><a href="/products?category=Home%20%26%20living">Home & living</a><a href="/products?category=Accessories">Accessories</a><a class="nav-deal" href="/products?deal=1">Good deals <span>Fresh</span></a></nav><form class="header-search" action="/products" role="search"><label class="sr-only" for="site-search">Search products and shops</label>${icon('search',19)}<input id="site-search" name="q" type="search" placeholder="Search something lovely…" autocomplete="off"><button type="submit" aria-label="Search">${icon('arrow',17)}</button></form><div class="header-actions"><a class="action-link dashboard-link" href="/dashboard">My dashboard</a><button class="header-icon" type="button" aria-label="Wishlist preview" data-action="wishlist">${icon('heart',20)}</button><button class="header-icon bag-button" type="button" aria-label="Shopping bag, 0 items" data-action="bag">${icon('cart',21)}<span class="bag-count">0</span></button></div></div><nav class="mobile-nav" aria-label="Mobile navigation"><a href="/">Discover</a><a href="/products">Shop all</a><a href="/products?category=Home%20%26%20living">Home & living</a><a href="/products?category=Accessories">Accessories</a><a href="/dashboard">My dashboard</a></nav></header>`;
}
function footer() { return `<footer class="site-footer"><a class="brand" href="/"><span class="brand-mark"><i></i><i></i><i></i><i></i></span><span>shop<span class="brand-accent">hub</span><span class="brand-period">.</span></span></a><span>Good finds, from good people.</span><span>© 2026 ShopHub</span><a href="/dashboard">Your account ${icon('arrow',14)}</a></footer>`; }
function sectionTitle(kicker, title, href = '/products', label = 'Explore all') { return `<div class="section-title"><div><p class="eyebrow">${kicker}</p><h2>${title}</h2></div><a class="text-link" href="${href}">${label} ${icon('arrow',16)}</a></div>`; }

function home() {
  return `${header('home')}<main class="home-main page-width"><section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="sparkle-dot">✳</span> A MARKETPLACE FOR THE GOOD STUFF</p><h1>Find things<br>that feel <em>like you.</em></h1><p>Meet independent makers, fall for thoughtful details, and bring home the pieces you’ll keep reaching for.</p><form class="hero-search" action="/products" role="search"><label class="sr-only" for="hero-search">What are you looking for?</label>${icon('search',20)}<input id="hero-search" name="q" type="search" placeholder="What are you looking for today?"><button type="submit" aria-label="Search">${icon('arrow',19)}</button></form><div class="hero-proof"><span class="proof-avatars"><i>M</i><i>S</i><i>A</i></span><span>Loved by 24,000+ thoughtful shoppers</span></div></div><div class="hero-visual"><img src="${photo('photo-1600210492486-724fe5c67fb0',1100)}" alt="A warm, sunlit living room with considered everyday objects"><div class="hero-note"><span class="hero-note__icon">✳</span><span><small>THE GOOD EDIT</small><strong>Objects for a slower Sunday</strong></span>${icon('arrow',18)}</div><div class="hero-caption">MADE WITH CARE. FOUND RIGHT HERE.</div></div><div class="hero-bottomline"><span>GOOD FINDS, GOOD PEOPLE</span><span>01 / 03</span></div></section>
  <section class="category-section" id="categories">${sectionTitle('A GOOD PLACE TO START','What are you in the mood for?','/products','All categories')}<div class="category-grid">${categories.map(([name,desc,img])=>`<a class="category-tile" href="/products?category=${encodeURIComponent(name)}"><span class="category-photo"><img src="${photo(img,520)}" alt="" loading="lazy"></span><span class="category-name">${name}${icon('arrow',15)}</span><span class="category-caption">${desc}</span></a>`).join('')}</div></section>
  <section class="deals-section"><div class="deal-copy"><p class="eyebrow">A GOOD LITTLE BONUS</p><h2>Worth a second look.</h2><p>Thoughtful things, at especially lovely prices. Your next favorite might be right here.</p><a class="button-primary" href="/products?deal=1">Shop the good deals ${icon('arrow',16)}</a><span class="deal-squiggle" aria-hidden="true">✳</span></div><div class="deal-items">${[products[2],products[6],products[0]].map(p=>`<a class="deal-mini" href="/products/${p.id}"><img src="${photo(p.image,420)}" alt="${p.alt}" loading="lazy"><span><small>${p.flag}</small><strong>${p.name}</strong><b>${dollars(p.price)} ${p.old ? `<s>${dollars(p.old)}</s>` : ''}</b></span>${icon('arrow',16)}</a>`).join('')}</div></section>
  <section class="product-section">${sectionTitle('MAKING THE ROUNDS','A few crowd favorites')}<div class="product-grid">${[products[0],products[3],products[1],products[8]].map(card).join('')}</div></section>
  <section class="maker-section"><div class="maker-photo"><img src="${photo('photo-1455390582262-044cdead277a',1000)}" alt="An independent maker at work in a sunlit studio" loading="lazy"><span>MADE SLOWLY, LOVED FOR LONGER</span></div><div class="maker-copy"><p class="eyebrow">A MARKETPLACE WITH A HUMAN SIDE</p><h2>Small shops.<br><em>Big heart.</em></h2><p>Behind every good find is a real person who cared enough to make it. Meet the independent shops putting thought into the things we bring home.</p><a class="button-light" href="/products?shop=Sunday%20Objects">Meet the makers ${icon('arrow',16)}</a><div class="maker-count"><strong>1,200+</strong><span>independent shops to discover</span></div></div></section>
  <section class="product-section recommended-section">${sectionTitle('A LITTLE SOMETHING FOR YOU','Picked with you in mind')}<div class="recommend-note">Based on the things thoughtful shoppers are loving lately.</div><div class="product-grid">${[products[4],products[7],products[9],products[10]].map(card).join('')}</div></section>
  <section class="recent-section">${sectionTitle('PICK UP WHERE YOU LEFT OFF','Recently admired','/products','See more finds')}<div class="recent-row">${[products[2],products[5],products[1]].map(p=>`<a class="recent-item" href="/products/${p.id}"><img src="${photo(p.image,340)}" alt="${p.alt}" loading="lazy"><span><small>${p.shop}</small><strong>${p.name}</strong><b>${dollars(p.price)}</b></span>${icon('arrow',16)}</a>`).join('')}</div></section></main>${footer()}`;
}

function listing() {
  const params = new URLSearchParams(location.search); const q = params.get('q') || ''; const category = params.get('category') || ''; const shop = params.get('shop') || ''; const deals = params.has('deal');
  document.title = q ? `Results for “${q}” — ShopHub` : `${category || shop || (deals ? 'Good deals' : 'Shop all finds')} — ShopHub`;
  const context = q ? `Search results for “${q}”` : category || shop || (deals ? 'Good deals' : 'All the good finds');
  const matches = products.filter(p => (!q || `${p.name} ${p.category} ${p.shop}`.toLowerCase().includes(q.toLowerCase())) && (!category || p.category === category) && (!shop || p.shop.toLowerCase() === shop.toLowerCase()) && (!deals || p.old));
  const count = matches.length;
  return `${header('products')}<main class="listing-main page-width"><div class="breadcrumbs"><a href="/">Discover</a>${icon('chevron',14)}<span>${context}</span></div><section class="listing-intro"><div><p class="eyebrow">THE SHOPHUB EDIT</p><h1>${context}</h1><p>Good things, made thoughtfully and ready to find a home.</p></div><div class="shipping-note">${icon('truck',19)} <span>Free shipping on orders over $75</span></div></section>
  <div class="shop-controls"><button class="filter-mobile" type="button" data-action="filter-toggle">${icon('settings',17)} Filters <span>${count}</span></button><div class="active-filters">${category ? `<button class="filter-chip" data-clear="category">${category} ${icon('close',13)}</button>` : ''}${shop ? `<button class="filter-chip" data-clear="shop">${shop} ${icon('close',13)}</button>` : ''}${q ? `<button class="filter-chip" data-clear="q">${q} ${icon('close',13)}</button>` : ''}${(category||shop||q)?'<a class="clear-filters" href="/products">Clear all</a>':''}</div><label class="sort-control">Sort by <select id="sort"><option value="featured">Featured</option><option value="rating">Top rated</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select>${icon('down',15)}</label></div>
  <div class="listing-layout"><aside class="filters" id="filters" aria-label="Product filters"><div class="filter-heading"><strong>Filters</strong><a href="/products">Reset all</a><button type="button" class="filter-close" aria-label="Close filters" data-action="filter-toggle">${icon('close',18)}</button></div><fieldset><legend>Category</legend>${['Home & living','Accessories','Shoes','Tech & audio','Outdoors'].map(c=>`<label class="check-option"><input type="checkbox" name="category" value="${c}" ${category===c?'checked':''}><span class="custom-check"></span>${c}<small>${products.filter(p=>p.category===c).length}</small></label>`).join('')}</fieldset><fieldset><legend>Price range</legend><div class="price-inputs"><label><span class="sr-only">Minimum price</span><span>$</span><input type="number" min="0" placeholder="0" value="${params.get('min')||''}" id="min-price"></label><span>to</span><label><span class="sr-only">Maximum price</span><span>$</span><input type="number" min="0" placeholder="150" value="${params.get('max')||''}" id="max-price"></label></div><button class="apply-price" type="button" data-action="price">Apply price</button></fieldset><fieldset><legend>Customer rating</legend>${[['4','4 stars & up'],['3','3 stars & up']].map(([v,l])=>`<label class="check-option"><input type="radio" name="rating" value="${v}" ${params.get('rating')===v?'checked':''}><span class="radio-check"></span>${l}<span class="stars-inline">${icon('star',13)}</span></label>`).join('')}</fieldset><fieldset><legend>Shop</legend>${['Sunday Objects','Marlow Goods','Common Ground','North & Tone','Kindred Supply','Wilder Home'].map(s=>`<label class="check-option"><input type="checkbox" name="shop" value="${s}" ${shop===s?'checked':''}><span class="custom-check"></span>${s}</label>`).join('')}</fieldset><fieldset class="last-filter"><legend>Availability</legend><label class="check-option"><input type="checkbox" name="stock" value="1"><span class="custom-check"></span>In stock</label></fieldset></aside>
  <section class="results-area" aria-labelledby="results-heading"><div class="results-meta"><h2 id="results-heading"><strong id="result-count">${count}</strong> thoughtful finds</h2><span>Prices shown in USD</span></div><div class="loading-grid" id="loading-state" aria-label="Loading products" style="display:grid"><div></div><div></div><div></div><div></div></div><div class="product-grid listing-grid" id="result-grid" hidden>${matches.slice(0,9).map(card).join('')}</div><div class="no-results" id="no-results" hidden><span class="no-results-icon">${icon('search',25)}</span><h2>No finds this time.</h2><p>Try a different search or clear a filter to see what’s out there.</p><a class="button-primary" href="/products">Browse all finds ${icon('arrow',16)}</a></div><nav class="pagination" aria-label="Product pages" hidden><button type="button" data-page="prev" disabled aria-label="Previous page">${icon('chevron',17)}</button><button type="button" class="page-current" data-page="1" aria-current="page">1</button><button type="button" data-page="2" ${count < 10 ? 'disabled' : ''}>2</button><button type="button" data-page="next" ${count < 10 ? 'disabled' : ''} aria-label="Next page">${icon('arrow',16)}</button><span>Showing <strong id="shown-count">${Math.min(count,9)}</strong> of ${count} finds</span></nav></section></div></main>${footer()}`;
}

function detail() {
  const id = decodeURIComponent(location.pathname.split('/').filter(Boolean).at(-1)); const p = products.find(x=>x.id===id) || products[0]; document.title = `${p.name} — ShopHub`;
  return `${header()}<main class="detail-main page-width"><div class="breadcrumbs"><a href="/">Discover</a>${icon('chevron',14)}<a href="/products?category=${encodeURIComponent(p.category)}">${p.category}</a>${icon('chevron',14)}<span>${p.name}</span></div><section class="detail-layout"><div class="gallery"><div class="gallery-main"><img id="main-image" src="${photo(p.image,1200)}" alt="${p.alt}"><span class="product-flag">${p.flag}</span><button class="gallery-save save-button" type="button" data-action="save" data-name="${p.name}" aria-pressed="false" aria-label="Save ${p.name}">${icon('heart',19)}</button></div><div class="gallery-thumbs"><button class="thumb is-active" data-image="${photo(p.image,1200)}" aria-label="View product image 1"><img src="${photo(p.image,180)}" alt=""></button><button class="thumb" data-image="${photo('photo-1523275335684-37898b6baf30',1200)}" aria-label="View product image 2"><img src="${photo('photo-1523275335684-37898b6baf30',180)}" alt=""></button><button class="thumb" data-image="${photo('photo-1526170375885-4d8ecf77b99f',1200)}" aria-label="View product image 3"><img src="${photo('photo-1526170375885-4d8ecf77b99f',180)}" alt=""></button><button class="thumb" data-image="${photo('photo-1490312278390-ab64016e0aa9',1200)}" aria-label="View product image 4"><img src="${photo('photo-1490312278390-ab64016e0aa9',180)}" alt=""></button></div><div class="gallery-caption">${icon('sparkle',15)} A real little something, chosen with care.</div></div>
  <div class="product-detail-copy"><div class="detail-topline"><a href="/products?shop=${encodeURIComponent(p.shop)}">${p.shop} <span class="verified-badge">✓ Verified shop</span></a><button class="share-link" data-action="share">Share ${icon('external',15)}</button></div><h1>${p.name}</h1><div class="detail-rating"><span>${icon('star',16)} ${p.rating}</span><a href="#reviews">${p.reviews} reviews</a><i></i><span class="stock-dot"></span> In stock</div><div class="detail-price">${dollars(p.price)} ${p.old?`<s>${dollars(p.old)}</s><span class="sale-pill">Save ${Math.round((1-p.price/p.old)*100)}%</span>`:''}</div><p class="detail-description">${p.detail}</p><div class="detail-trust-row"><span>${icon('truck',17)} Ships free over $75</span><span>${icon('check',17)} Easy 30-day returns</span></div><div class="variant-picker"><div><strong>Color</strong><span id="selected-color">${p.color}</span></div><div class="swatches"><button class="swatch swatch-sand selected" aria-label="Sand color" aria-pressed="true" data-color="${p.color}"></button><button class="swatch swatch-sage" aria-label="Sage color" aria-pressed="false" data-color="Sage"></button><button class="swatch swatch-clay" aria-label="Clay color" aria-pressed="false" data-color="Clay"></button></div></div><div class="purchase-row"><div class="quantity-control"><button type="button" aria-label="Decrease quantity" data-action="qty-down">−</button><output id="quantity">1</output><button type="button" aria-label="Increase quantity" data-action="qty-up">+</button></div><button class="button-primary add-product" data-action="purchase" data-name="${p.name}">${icon('cart',18)} Add to bag</button><button class="buy-now" data-action="buy" data-name="${p.name}">Buy now ${icon('arrow',16)}</button></div><div class="delivery-card">${icon('truck',20)}<span><strong>A good thing is on its way.</strong><small>Order today and it ships from ${p.shop} in 1–2 business days.</small></span></div><div class="accordion-list"><details open><summary>Meet the maker <span>${icon('down',15)}</span></summary><p>${p.shop} is an independent studio making useful, lasting pieces in small batches. Every order is packed with care and ships directly from the maker.</p></details><details><summary>Shipping & returns <span>${icon('down',15)}</span></summary><p>Carefully packed and dispatched in 1–2 business days. Returns are welcome within 30 days of delivery.</p></details><details><summary>Details & care <span>${icon('down',15)}</span></summary><p>${p.detail} Keep it looking its best with the care notes included in your package.</p></details></div></div></section>
  <section class="specs-section"><div class="specs-story"><p class="eyebrow">THE LITTLE DETAILS</p><h2>Good design<br><em>lives in the details.</em></h2><p>${p.detail}</p></div><div class="spec-table">${p.specs.map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('')}</div></section>
  <section class="reviews-section" id="reviews"><div class="review-summary"><p class="eyebrow">KIND WORDS FROM CUSTOMERS</p><h2>It’s getting lots of love.</h2><div class="review-score"><strong>${p.rating}</strong><span>${icon('star',17)}${icon('star',17)}${icon('star',17)}${icon('star',17)}${icon('star',17)}<small>Based on ${p.reviews} reviews</small></span></div><div class="rating-bars">${[5,4,3,2,1].map((n,i)=>`<div><span>${n} star</span><i><b style="width:${[78,16,4,1,1][i]}%"></b></i><small>${[78,16,4,1,1][i]}%</small></div>`).join('')}</div></div><div class="review-cards"><article><span class="review-stars">★★★★★</span><p>“So happy I found this little shop. The quality is lovely and it feels even more special in person.”</p><strong>Jamie R.</strong><small>Verified buyer · 2 weeks ago</small></article><article><span class="review-stars">★★★★★</span><p>“Exactly what I hoped for. Thoughtful packaging, fast shipping, and the details are just right.”</p><strong>Priya M.</strong><small>Verified buyer · 1 month ago</small></article></div></section>
  <section class="product-section">${sectionTitle('GOES NICELY WITH','More good things to discover')}<div class="product-grid">${products.filter(x=>x.id!==p.id).slice(0,4).map(card).join('')}</div></section></main>${footer()}`;
}

const path = location.pathname; const app = document.querySelector('#app');
app.innerHTML = path.startsWith('/products/') ? detail() : path.startsWith('/products') ? listing() : home();
const searchQuery = new URLSearchParams(location.search).get('q');
if(searchQuery) document.querySelectorAll('.header-search input').forEach(input=>input.value=searchQuery);

const toast = document.querySelector('#toast-region'); let toastTimer;
function notify(message) { toast.innerHTML = `${icon('check',18)}<span>${message}</span>`; toast.classList.add('is-visible'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toast.classList.remove('is-visible'),2400); }
let currentRows = [];
let currentPage = 1;
function showPage(page) {
  currentPage = Math.max(1, Math.min(page, Math.ceil(currentRows.length / 9)));
  const start = (currentPage - 1) * 9;
  document.querySelector('#result-grid').innerHTML = currentRows.slice(start, start + 9).map(card).join('');
  document.querySelector('#shown-count').textContent = Math.min(start + 9, currentRows.length);
  const nav = document.querySelector('.pagination');
  nav.querySelector('[data-page="1"]').classList.toggle('page-current', currentPage === 1);
  nav.querySelector('[data-page="2"]').classList.toggle('page-current', currentPage === 2);
  nav.querySelectorAll('[data-page="1"],[data-page="2"]').forEach(button=>button.setAttribute('aria-current',String(Number(button.dataset.page)===currentPage?'page':'false')));
  nav.querySelector('[data-page="prev"]').disabled = currentPage === 1;
  nav.querySelector('[data-page="next"]').disabled = currentPage >= Math.ceil(currentRows.length / 9);
}
function updateResults() {
  const params = new URLSearchParams(location.search); const cat = [...document.querySelectorAll('input[name="category"]:checked')].map(e=>e.value); const shop = [...document.querySelectorAll('input[name="shop"]:checked')].map(e=>e.value); const rating = document.querySelector('input[name="rating"]:checked')?.value; const min = Number(document.querySelector('#min-price')?.value||0); const max = Number(document.querySelector('#max-price')?.value||9999); const query = params.get('q')||'';
  const rows = products.filter(p=>(!query||`${p.name} ${p.category} ${p.shop}`.toLowerCase().includes(query.toLowerCase()))&&(!cat.length||cat.includes(p.category))&&(!shop.length||shop.includes(p.shop))&&p.price>=min&&p.price<=max&&(!rating||Number(p.rating)>=Number(rating))&&(!params.has('deal')||p.old));
  const order=document.querySelector('#sort')?.value; if(order==='rating') rows.sort((a,b)=>Number(b.rating)-Number(a.rating)); if(order==='price-low') rows.sort((a,b)=>a.price-b.price); if(order==='price-high') rows.sort((a,b)=>b.price-a.price);
  currentRows=rows; currentPage=1; showPage(1); document.querySelector('#result-grid').hidden=false; document.querySelector('#result-count').textContent=rows.length; document.querySelector('#no-results').hidden=Boolean(rows.length); document.querySelector('.pagination').hidden=rows.length<=9;
}
document.addEventListener('change',e=>{if(e.target.matches('#sort,input[name="category"],input[name="shop"],input[name="rating"]')) updateResults();});
document.addEventListener('click',e=>{
  const action=e.target.closest('[data-action]'); const clear=e.target.closest('[data-clear]');
  if(clear){const u=new URL(location.href);u.searchParams.delete(clear.dataset.clear);location.href=u.pathname+u.search;return;}
  const pageButton=e.target.closest('[data-page]'); if(pageButton&&!pageButton.disabled){const requested=pageButton.dataset.page;showPage(requested==='prev'?currentPage-1:requested==='next'?currentPage+1:Number(requested));document.querySelector('#results-heading').scrollIntoView({behavior:'smooth',block:'start'});return;}
  if(e.target.closest('[data-image]')){const t=e.target.closest('[data-image]');document.querySelector('#main-image').src=t.dataset.image;document.querySelectorAll('.thumb').forEach(x=>x.classList.toggle('is-active',x===t));return;}
  if(e.target.closest('[data-color]')){const t=e.target.closest('[data-color]');document.querySelector('#selected-color').textContent=t.dataset.color;document.querySelectorAll('.swatch').forEach(x=>{x.classList.toggle('selected',x===t);x.setAttribute('aria-pressed',String(x===t));});return;}
  if(!action)return;
  if(action.dataset.action==='save'){const on=action.getAttribute('aria-pressed')!=='true';action.setAttribute('aria-pressed',String(on));action.classList.toggle('is-saved',on);notify(on?`${action.dataset.name} saved to your wishlist`:`${action.dataset.name} removed from your wishlist`);}
  if(action.dataset.action==='add'||action.dataset.action==='purchase'||action.dataset.action==='buy'){const count=document.querySelector('.bag-count');count.textContent=String(Number(count.textContent)+Number(document.querySelector('#quantity')?.value||1));document.querySelector('.bag-button').setAttribute('aria-label',`Shopping bag, ${count.textContent} items`);notify(`${action.dataset.name} added to your bag`);}
  if(action.dataset.action==='wishlist') notify('Your saved finds will be waiting when you sign in.');
  if(action.dataset.action==='bag') notify('Your shopping bag is ready for something lovely.');
  if(action.dataset.action==='share'){navigator.clipboard?.writeText(location.href).then(()=>notify('Product link copied')).catch(()=>notify('Product link ready to share'));}
  if(action.dataset.action==='qty-down'||action.dataset.action==='qty-up'){const out=document.querySelector('#quantity');out.value=String(Math.max(1,Number(out.value)+(action.dataset.action==='qty-up'?1:-1)));}
  if(action.dataset.action==='menu'){const nav=document.querySelector('.mobile-nav');const open=nav.classList.toggle('is-open');action.setAttribute('aria-expanded',String(open));}
  if(action.dataset.action==='filter-toggle'){document.querySelector('#filters')?.classList.toggle('filters-open');}
  if(action.dataset.action==='price')updateResults();
});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.mobile-nav')?.classList.remove('is-open');document.querySelector('#filters')?.classList.remove('filters-open');}});
if(path.startsWith('/products')&&!path.startsWith('/products/')){const params=new URLSearchParams(location.search);const query=params.get('q')||'';const category=params.get('category')||'';const shop=params.get('shop')||'';currentRows=products.filter(p=>(!query||`${p.name} ${p.category} ${p.shop}`.toLowerCase().includes(query.toLowerCase()))&&(!category||p.category===category)&&(!shop||p.shop.toLowerCase()===shop.toLowerCase())&&(!params.has('deal')||p.old));showPage(1);setTimeout(()=>{document.querySelector('#loading-state')?.remove();document.querySelector('#result-grid').hidden=false;document.querySelector('#no-results').hidden=currentRows.length>0;document.querySelector('.pagination').hidden=currentRows.length<=9;},420);}
